### ISSUE TITLE
.deb package not working on debian

### ISSUE THREAD

**Issue by larsmm** [sk1project/uniconvertor#13]
I am unable to install .deb file. Dependency liblcms2 does not exist in repo. There is a package named liblcms2-2. I installed it but it did not help.

**Comment by sk1project** [comment]
Which package have you tried installing and which Debian version are you using?

**Comment by Moini** [comment]
@larsmm You can build the package yourself, but you need to change the requirements listed in the configuration.

littlecms is now liblcms2-2 , and python imaging is now python-pil. Updating those dependencies make it work for me on Linux Mint 19.1 (probably will also work for you on Debian).

I've appended the two files:

[changed_files_for_Ubuntu_18.04.zip](https://github.com/sk1project/uniconvertor/files/2948647/changed_files_for_Ubuntu_18.04.zip)

@sk1project You probably don't take these as pull requests anymore? (I also wouldn't know how to do alternatives...)

**Comment by sk1project** [comment]
@Moini it seems you try fixing UniConvertor 1.x package. This UC version is obsolete. Upcoming UC 2.0 is much more better including deps for different distros.
https://sk1project.net/viewpage.php?page_id=26

**Comment by Moini** [comment]
@sk1project Thanks for letting me know!

I needed something in between, for being able to give Inkscape user support for 0.92.4, and figured it would be nice to share with those who need it.

Inkscape had to throw uniconvertor out :-( , so Inkscape 1.0 won't be able to convert to plt (and some more?) anymore in the next major version. It's a real pity.

Do you already know when uniconvertor 2.0 will be ready? Will it be Python 3 compatible?

**Comment by sk1project** [comment]
@Moini hope we will release UniConvertor 2.0 and sK1 2.0 (so some users can throw Inkscape out ;) ) before LGM2019 (end of May). There will be a lot of interesting features dealing with Corel formats including export into CDR file format. Throwing out UniConvertor, Inkscape lost CGM, CMX, CCX, CDRX support. Thus sK1 2.0 will be powered by some unique features.

Py3 migration is scheduled on this summer. We cannot start migration before due to wxpython (sK1 2.0 dependency). Fortunately wxpython for py3 is available now. So we could resolving this issue.

**Comment by Moini** [comment]
Thank you again, @sk1project ! Will you be at LGM, too? Inkscapers plan to hold a short two-day hackfest before LGM, and many will probably stay for a couple of days after. I think they might enjoy to meet up with other vector graphics people.

Yes, I agree, losing those export formats is quite sad... From what you write here, I'm hopeful that they can be back soon, then. I didn't know that wxpython was the blocker for you.

(sK1 has more than just those export formats as features that set it apart - CMYK, for example!)

**Comment by sk1project** [comment]
@Moini we will be there definitely but we have not decided about exact arriving date. I think even regular LGM days will be enough to meet up because real work will be online after the conference.

UPD: as I see in LGM schedule draft my presentation will be May 30, so I should be there one or two days before.

**Comment by Moini** [comment]
Ah, you present, about Corel compatibility :), very good! 

And aaaah, the schedule is out! I'm sure there will be opportunities to meet, then! I suppose there will also be Inkscape devs attending your talk. I don't know yet if I'll be there, too.
